### ISSUE TITLE
Obligations:Period Key for VAT Submission Error response

### ISSUE THREAD

**Issue by crazypabs** [hmrc/obligations-api#66]
Hi

I am passing the following via curl on the test api for VAT to submit a return:

`$strURL = "https://test-api.service.hmrc.gov.uk/organisations/vat/{vrn}/obligations/?from=2021-01-01&to=2021-03-31&status=O&scope=write:vat";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,			$strURL);
curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch, CURLOPT_TIMEOUT,		3);
curl_setopt($ch, CURLOPT_HTTPGET,		true);
$varHeadersPeriodKey = 	array(
						"accept:application/vnd.hmrc.1.0+json",
						"authorization:Bearer abc123dohrayme"
						);
curl_setopt($ch, CURLOPT_HTTPHEADER, $varHeadersPeriodKey);
$contentPeriodKey = trim(curl_exec($ch));
curl_close($ch);`

however when my response comes back all i seem to be getting is: 
`{
    "code": "INVALID_SCOPE",
    "message": "Can not access the required resource. Ensure this token has all the required scopes."
}`

I cant find anywhere the sample curl code that i should be using for this.
I have attempted to include the scope into above and i am using the same scope to retrieve the Token once the oAuth has granted me the code.

How do i go about retrieving the period key please.

Kind regards

M@

**Comment by hmrc-api-team** [comment]
Hi @crazypabs 

The URL you are calling is a URL on the [VAT API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0), it doesn't exist in the [Obligations API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/obligations-api/1.0).

Just to point you in the right direction though - the endpoint you are calling here is the [Retrieve VAT obligations](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion) endpoint, not the [Submit a VAT return for period](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion) endpoint. The Retrieve VAT obligations endpoint requires a scope of `read:vat` not `write:vat` - make sure that all required scopes are assigned when you are generating your bearer token. The error you're getting is saying that you are using a bearer token with the wrong scope.

If you have any further questions, please search for or open an Issue on the [hmrc/vat-api](https://github.com/hmrc/vat-api/issues).

Kind regards
